### ISSUE TITLE
 Execute Django tests in GitHub Actions

### ISSUE THREAD

**Issue by zkan** [dataength/dataengnews#4]

**Comment by Thoritie** [comment]
I'm on it

**Comment by SoumyaRanjanNaik** [comment]
Can I build a Action to run django's own manage.py test command and test the app ?

**Comment by zkan** [comment]
@SoumyaRanjanNaik Yes, you can. Eventhough at the end I'll use Pytest as a main testing tool, your PR is still very welcome. :)

**Comment by SoumyaRanjanNaik** [comment]
Then I would include pytest as well as manage.py test so both can be run to cover any kind of testing.
