### ISSUE TITLE
Complete the News model

### ISSUE THREAD

**Issue by zkan** [dataength/dataengnews#7]
See the screenshot below.

![Screen Shot 2563-10-09 at 09 56 21](https://user-images.githubusercontent.com/704794/95536659-b14aea80-0a15-11eb-9ed8-03120c1a2878.png)

We should be able to save a news with either the title and URL or text.

**Comment by liisberg** [comment]
I can take care of this, please assign it to me.

**Comment by zkan** [comment]
@liisberg Cool, thanks! Assigned. :)
